Update package.json
Fix error:

````
Error: Cannot find module 'babel-runtime/helpers/class-call-check'                                                              [350/1882]
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/code/node_modules/zombie/lib/index.js:3:23)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/code/node_modules/babel/lib/babel/api/register/node.js:130:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    ....
````